#!/bin/bash
rm results.txt

java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-00.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-01.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-02.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-03.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-04.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-05.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-06.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-07.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-08.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-09.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-10.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-11.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-12.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-13.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-14.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-15.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-16.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-17.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-18.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App is-invalid-batch ../../sample-data/batch-19.json

java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-00.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-01.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-02.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-03.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-04.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-05.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-06.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-07.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-08.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-09.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-10.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-11.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-12.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-13.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-14.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-15.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-16.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-17.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-18.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App waste-metric ../../sample-data/batch-19.json

java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-00.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-01.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-02.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-03.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-04.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-05.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-06.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-07.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-08.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-09.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-10.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-11.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-12.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-13.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-14.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-15.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-16.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-17.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-18.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App one-swap-recommendation ../../sample-data/batch-19.json

java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-00.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-01.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-02.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-03.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-04.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-05.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-06.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-07.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-08.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-09.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-10.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-11.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-12.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-13.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-14.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-15.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-16.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-17.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-18.json
java -cp target/batch-analyzer-1.0-SNAPSHOT.jar com.fortysevenlining.app.App two-swap-recommendation ../../sample-data/batch-19.json